# Generated by Django 2.2.25 on 2022-01-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidocredential',
            name='credential_name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
