# Generated by Django 2.1.7 on 2019-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='acc_from',
        ),
        migrations.AlterField(
            model_name='rule',
            name='acc_to',
            field=models.CharField(blank=True, max_length=512, verbose_name='Account'),
        ),
    ]
