# Generated by Django 2.1.7 on 2019-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_submit', '0002_auto_20190528_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='acc_to',
            new_name='account',
        ),
    ]
