# Generated by Django 2.1.7 on 2019-05-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_submit', '0003_auto_20190528_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
