# Generated by Django 2.1.7 on 2019-05-31 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger_submit', '0004_rule_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='new_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='payee',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('payee', 'user', 'comment')},
        ),
    ]
