# Generated by Django 2.1.7 on 2019-05-31 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger_submit', '0005_auto_20190531_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='new_comment',
            new_name='new_note',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='comment',
            new_name='note',
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('payee', 'user', 'note')},
        ),
    ]
