# Generated by Django 2.1.7 on 2019-05-08 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerpath',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ledger_path', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
