# Generated by Django 2.1.7 on 2019-05-09 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('ledger_ui', '0002_auto_20190508_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_entry', models.BinaryField()),
                ('old_position', models.PositiveIntegerField()),
                ('new_position', models.PositiveIntegerField()),
            ],
        ),
    ]
