# Generated by Django 2.1.7 on 2019-05-28 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_ui', '0004_auto_20190525_0357'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Undo',
        ),
        migrations.CreateModel(
            name='Undo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_entry_pickle', models.BinaryField()),
                ('old_position', models.PositiveIntegerField()),
                ('new_position', models.PositiveIntegerField()),
            ],
        ),
    ]
